steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-flask-python-api', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/simple-flask-python-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'simple-flask-python', '--image', 'gcr.io/$PROJECT_ID/simple-flask-python-api', '--platform', 'managed']
