steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/simple-api', '-f workspace/cloud-build-labs/flask-python-simple/simple-flask-python/Dockerfile']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/bexup-devopslabs/simple-flask-python-api']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'simple-flask-python', '--image', 'gcr.io/bexup-devopslabs/simple-flask-python-api', '--platform', 'managed']
